version: '3'

services:
  app:
    hostname: app
    build: './src/front'
    volumes:
      - './src/front:/app'
    ports:
      - '80:3000'

  api:
    hostname: api
    build: './src/back/api'
    restart: always
    ports: 
      - '3000:80'

  api_users_login:
    hostname: api_users_login
    image: nginx:alpine
    restart: always
    volumes:
      - './html:/usr/share/nginx/html/api/v1/users/login'
  
  api_users_register:
    hostname: api_users_register
    image: nginx:alpine
    restart: always
    volumes:
      - './html:/usr/share/nginx/html/api/v1/users/register'
  
  api_tasks_list:
    hostname: api_tasks_list
    image: nginx:alpine
    restart: always
    volumes:
      - './html:/usr/share/nginx/html/api/v1/tasks/list'
  
  api_tasks_create:
    hostname: api_tasks_create
    image: nginx:alpine
    restart: always
    volumes:
      - './html:/usr/share/nginx/html/api/v1/tasks/create'
  
  api_tasks_update:
    hostname: api_tasks_update
    image: nginx:alpine
    restart: always
    volumes:
      - './html:/usr/share/nginx/html/api/v1/tasks/update'
  
  api_tasks_finish:
    hostname: api_tasks_finish
    image: nginx:alpine
    restart: always
    volumes:
      - './html:/usr/share/nginx/html/api/v1/tasks/finish'
