version: '3'

services:

  app:
    hostname: app
    build: './src/front'
    volumes:
      - './src/front:/app'
    ports:
      - '80:3000'

  api:
    hostname: api
    build: './src/back/api'
    restart: always
    ports: 
      - '3000:80'

  api_users_login:
    hostname: api_users_login
    build: './src/back/users-login'
    restart: always
    volumes:
      - './src/back/users-login:/challenge/app'
      - './src/back/commons:/challenge/commons'
      - './data:/data'
      - './logs:/logs'

  api_users_register:
    hostname: api_users_register
    build: './src/back/users-register'
    restart: always
    volumes:
      - './src/back/users-register:/challenge/app'
      - './src/back/commons:/challenge/commons'
      - './data:/data'
      - './logs:/logs'

  api_tasks_list:
    hostname: 'api_tasks_list'
    build: './src/back/tasks-list/'
    restart: always
    volumes:
      - './src/back/tasks-list/:/challenge/app'
      - './src/back/commons/:/challenge/commons'
      - './data:/data'
      - './logs:/logs'

  api_tasks_create:
    hostname: 'api_tasks_create'
    build: './src/back/tasks-create/'
    restart: always
    volumes:
      - './src/back/tasks-create/:/challenge/app'
      - './src/back/commons/:/challenge/commons'
      - './data:/data'
      - './logs:/logs'

  api_tasks_update:
    hostname: 'api_tasks_update'
    build: './src/back/tasks-update/'
    restart: always
    volumes:
      - './src/back/tasks-update/:/challenge/app'
      - './src/back/commons/:/challenge/commons'
      - './data:/data'
      - './logs:/logs'

  api_tasks_finish:
    hostname: 'api_tasks_finish'
    build: './src/back/tasks-finish/'
    restart: always
    volumes:
      - './src/back/tasks-finish/:/challenge/app'
      - './src/back/commons/:/challenge/commons'
      - './data:/data'
      - './logs:/logs'
