name: Pushing to AWS Lightsail

on:
  schedule:
    - cron: '45 * * * *'
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out repository code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up AWS
        uses: aws-actions/setup-sam@v2
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: docker pull tmvdl/challenges:ubistart
      - run: curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
      - run: sudo chmod +x /usr/local/bin/lightsailctl
      -
        name: Pushing
        run: aws lightsail push-container-image --region us-east-1 --service-name ubistart-docker-1 --label tmvdl/challenges --image tmvdl/challenges:ubistart

