name: Push to Docker Hub

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up BuildX action
        uses: docker/setup-buildx-action@v1
      -
        name: Docker Hub Login
        uses: docker/login-action@v1 
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}
      -
        name: Docker Build
        run: docker build --network host --no-cache -t tmvdl/challenges:ubistart .
      -
        name: Docker Tag
        run: docker push tmvdl/challenges:ubistart
