name: Pushing to Docker Hub

on:
  schedule:
    - cron: '10 * * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out repository code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKER }}
      -
        name: Build and Tag
        run: sh ./env/production/build.sh
      -
        name: Push
        run: docker push tmvdl/challenges -a
